// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ferromax.Data;

namespace ferromax.Migrations
{
    [DbContext(typeof(FerromaxContext))]
    [Migration("20221206150517_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ferromax.Models.Compras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precioCompra")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("compras");
                });

            modelBuilder.Entity("ferromax.Models.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidosEmpleados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailEmpleados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombresEmpleados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefonoEmpleados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("ferromax.Models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreProductos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precioProducto")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("ferromax.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidosRepartidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreRepartidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productoProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefonoRepartidor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("proveedors");
                });

            modelBuilder.Entity("ferromax.Models.Ventas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precioVenta")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
